name: Publish
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Determine last published version of parse-ical
        run: |
          set +e # disable pipefail, error handling is done manually below
          # get version or fall back to `0.0.0` if the package doesn't exist (yet)
          echo "NPM_PUBLISHED_VERSION=$(npm show parse-ical version || echo "0.0.0")" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - id: version-metadata
        uses: Quantco/ui-actions/version-metadata@v1.0.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: publish
        uses: Quantco/ui-actions/publish@v1.0.15
        with:
          increment-type: minor
          relevant-files: '["**/*"]'
          latest-registry-version: ${{ env.NPM_PUBLISHED_VERSION }}
          version-metadata-json: ${{ steps.version-metadata.outputs.json }}

      - if: steps.publish.outputs.publish == 'true'
        name: Publish
        run: |
          pnpm install
          pnpm lint
          pnpm build
          pnpm test
          echo "Publishing version ${{ steps.publish.outputs.version }}"
          npm version --git-tag-version false --allow-same-version true ${{ steps.publish.outputs.version }}
          # TODO: commented out for now, will comment in once the first stable version is ready
          pnpm publish --no-git-checks --access public

      - name: Create action summary
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
        env:
          SUMMARY: ${{ steps.publish.outputs.reason }}
